# Generated by Django 5.0 on 2024-02-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.BigIntegerField(unique=True)),
                ('thread_id', models.BigIntegerField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Группа админов бота',
                'verbose_name_plural': 'Группы админов бота',
                'db_table': 'admin_group',
            },
        ),
        migrations.CreateModel(
            name='BotButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_name', models.CharField(max_length=255, unique=True, verbose_name='Название кнопки')),
                ('display_name', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Отображаемое имя')),
                ('text', models.CharField(default='Кнопка', max_length=55, verbose_name='Текст кнопки')),
            ],
            options={
                'verbose_name': 'Кнопка бота',
                'verbose_name_plural': 'Кнопки бота',
                'db_table': 'bot_buttons',
            },
        ),
        migrations.CreateModel(
            name='BotManagers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_link', models.CharField(max_length=255, verbose_name='Ссылка на менеджера')),
                ('manager_phone', models.CharField(max_length=255, verbose_name='Телефон менеджера')),
            ],
            options={
                'verbose_name': 'Менеджер бота',
                'verbose_name_plural': 'Менеджеры бота',
                'db_table': 'bot_managers',
            },
        ),
        migrations.CreateModel(
            name='BotMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_name', models.CharField(max_length=255, unique=True, verbose_name='Название сообщения')),
                ('display_name', models.CharField(max_length=255, unique=True, verbose_name='Отображаемое имя')),
                ('text', models.CharField(max_length=1024, verbose_name='Текст сообщения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Сообщение бота',
                'verbose_name_plural': 'Сообщения бота',
                'db_table': 'bot_messages',
            },
        ),
        migrations.CreateModel(
            name='BotStandartButtons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(default='Поделиться контактом', max_length=55, verbose_name="Кнопка 'Поделиться контактом'")),
                ('location', models.CharField(default='Поделиться местоположением', max_length=55, verbose_name="Кнопка 'Поделиться местоположением'")),
            ],
            options={
                'verbose_name': 'Стандартные кнопки бота',
                'verbose_name_plural': 'Стандартные кнопки бота',
                'db_table': 'bot_standart_buttons',
            },
        ),
    ]
