# Generated by Django 5.0 on 2024-10-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_settings', '0002_alter_admingroup_group_id_alter_admingroup_thread_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmessages',
            name='text',
            field=models.TextField(max_length=1024, verbose_name='Текст сообщения'),
        ),
    ]
