[bot_settings]
config_type = "BIG"
get_from = "db"
admin_id = 629562021
admin_commands = ["set_group", "set_thread"]
commands = ["start", "end"]
start_state = "union"

[bitrix]
user_fields_prefix = "UF_CRM_"
user_fields = ["PAID_FOR", "READY_ISSUED", "ISSUED", 
                "ORDER_DATA", "ORDER_PHOTO", "THINGS", 
                "CLIENT_COMMENT", "ISSUED_POINT"]

[bitrix.PAID_FOR]
FIELD_NAME = "PAID_FOR"
USER_TYPE_ID = "boolean"
SORT = 100
MANDATORY = "N"
LIST_COLUMN_LABEL = "Оплачено"
LIST_FILTER_LABEL = "Оплачено"
EDIT_FORM_LABEL = "Оплачено"
EDIT_IN_LIST = "Y"
XML_ID = "UF_PAID_FOR"

[bitrix.READY_ISSUED]
FIELD_NAME = "READY_ISSUED"
USER_TYPE_ID = "boolean"
SORT = 100
MANDATORY = "N"
LIST_COLUMN_LABEL = "Готово к выдаче"
LIST_FILTER_LABEL = "Готово к выдаче"
EDIT_FORM_LABEL = "Готово к выдаче"
EDIT_IN_LIST = "Y"
XML_ID = "UF_READY_ISSUED"

[bitrix.ISSUED]
FIELD_NAME = "ISSUED"
USER_TYPE_ID = "boolean"
SORT = 100
MANDATORY = "N"
LIST_COLUMN_LABEL = "Выдано"
LIST_FILTER_LABEL = "Выдано"
EDIT_FORM_LABEL = "Выдано"
EDIT_IN_LIST = "Y"
XML_ID = "UF_ISSUED"

[bitrix.ORDER_DATA]
FIELD_NAME = "ORDER_DATA"
USER_TYPE_ID = "string"
MANDATORY = "N"
LIST_COLUMN_LABEL = "Данные заказа"
LIST_FILTER_LABEL = "Данные заказа"
EDIT_FORM_LABEL = "Данные заказа"
EDIT_IN_LIST = "Y"
XML_ID = "UF_ORDER_DATA"
SETTINGS={ROWS=3,DEFAULT_VALUE=""}

[bitrix.CLIENT_COMMENT]
FIELD_NAME = "CLIENT_COMMENT"
USER_TYPE_ID = "string"
MANDATORY = "N"
LIST_COLUMN_LABEL = "Комментарий о заказе"
LIST_FILTER_LABEL = "Комментарий о заказе"
EDIT_FORM_LABEL = "Комментарий о заказе"
EDIT_IN_LIST = "Y"
XML_ID = "UF_CLIENT_COMMENT"
SETTINGS={ROWS=3,DEFAULT_VALUE="Комментария нет"}

[bitrix.ISSUED_POINT]
FIELD_NAME = "ISSUED_POINT"
USER_TYPE_ID = "string"
MANDATORY = "N"
LIST_COLUMN_LABEL = "Пункт выдачи"
LIST_FILTER_LABEL = "Пункт выдачи"
EDIT_FORM_LABEL = "Пункт выдачи"
EDIT_IN_LIST = "Y"
XML_ID = "UF_ISSUED_POINT"
SETTINGS={ROWS=3,DEFAULT_VALUE="Пункта нет"}

[bitrix.ORDER_PHOTO]
FIELD_NAME = "ORDER_PHOTO"
USER_TYPE_ID = "url"
MANDATORY = "N"
LIST_COLUMN_LABEL = "Фото заказа"
LIST_FILTER_LABEL = "Фото заказа"
EDIT_FORM_LABEL = "Фото заказа"
EDIT_IN_LIST = "Y"
XML_ID = "UF_ORDER_PHOTO"

[bitrix.THINGS]
FIELD_NAME = "THINGS"
USER_TYPE_ID = "enumeration"
MANDATORY = "N"
MULTIPLE = "Y"
LIST_COLUMN_LABEL = "Вещи"
LIST_FILTER_LABEL = "Вещи"
EDIT_FORM_LABEL = "Вещи"
EDIT_IN_LIST = "Y"
XML_ID = "UF_THINGS"


[messages]
messages_list = ["first", "info", "write_fio", "write_phone", 
                "write_email", "user_agreement", "subscribe", "menu",
                "choice_service", "choice_type_item", "choice_wear_treat", "choice_del_item", 
                "accept_add", "accept_del", "hand_over_menu",
                "order_get_photo", "order_success",
                "my_orders", "in_work", "ready_issue", "completed", 
                "select_area_group", "select_area_subgroup","select_point",
                "our_points", "contacts", "support", "faq",
                "feedback_points", "feedback_rate", "feedback_request", "feedback_send", 
                "feedback_content_error", "successful_request"]

[messages.first]
display_name = "Приветственное сообщение"
text = "Приветствую Вас в нашем боте. Пожалуйста, ознакомьтесь с информацией и пройдите регистрацию."
image = false
video = false

[messages.info]
display_name = "Информация"
text = """📄**Информация по боту**📄
С помощью нашего бота, Вы можете:
1. Формировать заказ на услуги химчистки в кратчайшее время; ✔️
2. Получать оповещения о Ваших заказах; ✔️
3. Оплачивать услуги удобным для Вас способом. ✔️

🪪 Для использования бота необходимо пройти регистрацию 🪪.
"""
image = false
video = false

[messages.write_fio]
display_name = "Запрос ФИО"
text = "🖋 Введите Ваше ФИО"
image = false
video = false

[messages.write_phone]
display_name = "Запрос телефона"
text = "📞 Отправьте номер телефона:"
image = false
video = false

[messages.write_email]
display_name = "Запрос почты"
text = "✉️ Введите Ваш e-mail:"
image = false
video = false

[messages.user_agreement]
display_name = "Пользовательское соглашение"
text = "Ознакомьтесь с пользовательским соглашением 📋"
image = false
video = false

[messages.subscribe]
display_name = "Запрос подписки"
text = "📬 Хотите получать информацию о новых акциях и специальных предложениях? 📬"
image = false
video = false

[messages.menu]
display_name = "Меню"
text = "💬 Здравствуйте! Выберите действие: ⌛️"
image = false
video = false

[messages.choice_service]
display_name = "Выбор доп. услуги"
text = "📝 Выберите интересующую Вас доп. услугу 📝"
image = false
video = false

[messages.choice_type_item]
display_name = "Выбор типа вещи"
text = "🥼 Какой тип вещи? 👕"
image = false
video = false

[messages.choice_del_item]
display_name = "Выбор удаления вещи"
text = "Какие вещи собираетесь убрать?"
image = false
video = false

[messages.choice_wear_treat]
display_name = "Выбор износа одежды"
text = "🪢 Выберите износ одежды: 🪢"
image = false
video = false

[messages.accept_add]
display_name = "Сообщение 'Подтвердить добавление'"
text = "Подтвердите добавление"
image = false
video = false

[messages.accept_del]
display_name = "Сообщение 'Подтвердить удаление'"
text = "Подтвердить удаление"
image = false
video = false

[messages.hand_over_menu]
display_name = "Сообщение 'Меню сдачи вещей'"
text = "Выберите действие 🖊"
image = false
video = false

[messages.order_get_photo]
display_name = "Запрос фото пломбы"
text = "Приложите фото пломбы"
image = false
video = false

[messages.order_success]
display_name = "Заказ оформлен"
text = "Ваш заказ {{number}} оформлен."
image = false
video = false

[messages.my_orders]
display_name = "Сообщение 'Мои заказы'"
text = "Какие заказы Вы хотите просмотреть?"
image = false
video = false

[messages.in_work]
display_name = "Сообщение 'В работе'"
text = "📘 Выберите заказ в работе. ⏳"
image = false
video = false

[messages.ready_issue]
display_name = "Сообщение 'Готовы'"
text = "📙 Выберите заказы готовые к выдаче. 📦"
image = false
video = false

[messages.completed]
display_name = "Сообщение 'Завершен'"
text = "📗 Выберите завершенные заказы. ✅"
image = false
video = false

[messages.select_area_group]
display_name = "Сообщение 'Выбор региона'"
text = "Выберите регион"
image = false
video = false

[messages.select_area_subgroup]
display_name = "Сообщение 'Выбор участка региона'"
text = "Выберите участок региона"
image = false
video = false

[messages.select_point]
display_name = "Сообщение выбора пункта"
text = "Выберите пункт"
image = false
video = false

[messages.our_points]
display_name = "Сообщение 'Наши пункты'"
text = "🖼 Какие пункты Вы хотите просмотреть? 🖼"
image = false
video = false

[messages.feedback_points]
display_name = "Сообщение 'Выбора пункта для отзыва'"
text = "Выберите пункт:"
image = false
video = false

[messages.feedback_rate]
display_name = "Сообщение 'Выбора оценки для отзыва'"
text = "Выберите рейтинг:"
image = false
video = false

[messages.feedback_request]
display_name = "Сообщение 'Запрос комментария'"
text = "Напишите комментарий к отзыву, не более 800 символов, при желании можно добавить картинку"
image = false
video = false

[messages.feedback_send]
display_name = "Сообщение 'Отзыв отправлен'"
text = "Ваш отзыв был отправлен, спасибо за обратную связь 🙏"
image = false
video = false

[messages.feedback_content_error]
display_name = "Сообщение ошибки комментария"
text = "Отзыв должен содержать текст или изображение с текстом, не более 800 символов в тексте"
image = false
video = false

[messages.contacts]
display_name = "Сообщение 'Контакты'"
text = "📞 Список контактов: 📞"
image = false
video = false

[messages.support]
display_name = "Сообщение 'Поддержка'"
text = "👩‍💻 Ссылки на менеджеров поддержки: 👩‍💻"

[messages.faq]
display_name = "Частые вопросы"
text = "❔ Частые вопросы ❔"
image = false
video = false

[messages.successful_request]
display_name = "Успешная обработка заявки"
text = "Заявка успешно обработана, ожидайте, данные по оплате будут отправлены вам в ближайшее время"
image = false
video = false

[buttons]
button_list = ["button__contact", "button__location", "menu", "back", 
                "continue", "stop", "yes", "no",  "hand_over", "make_order", "add_item", "del_item",
                "my_orders", "complete", "in_work", "ready", "points", 
                "feedback", "faq", "contacts", "support", "agree", "order_hand_over"]

[buttons.button__contact]
display_name = "Кнопка 'Поделиться контактом'"
text = "☎️ Поделиться контактом ☎️"

[buttons.button__location]
display_name = "Кнопка 'Поделиться местоположение'"
text = "Поделиться местоположением"

[buttons.menu]
display_name = "Кнопка меню"
text = "Меню 🔝"

[buttons.back]
display_name = "Кнопка назад"
text = "Назад 🔙"

[buttons.continue]
display_name = "Кнопка продолжить"
text = "Продолжить 🔜"

[buttons.stop]
display_name = "Кнопка остановить"
text = "Остановить 🔘"

[buttons.yes]
display_name = "Кнопка 'Да'"
text = "Да ✅"

[buttons.agree]
display_name = "Кнопка 'Согласен'"
text = "Согласен ✅"

[buttons.no]
display_name = "Кнопка 'Нет'"
text = "Нет ❌"

[buttons.hand_over]
display_name = "Кнопка 'сдать вещь' в меню"
text = "🧺 Сдать вещь 🧺"

[buttons.make_order]
display_name = "Кнопка 'Оформить заказ'"
text = "Оформить заказ 📝"

[buttons.add_item]
display_name = "Кнопка 'добавить вещь'"
text = "Добавить вещь ➕"

[buttons.del_item]
display_name = "Кнопка 'убрать вещь'"
text = "Убрать вещь ➖"

[buttons.order_hand_over]
display_name = "Кнопка 'сдать вещь' для заказа"
text = "Сдать ✅"

[buttons.my_orders]
display_name = "Кнопка 'мои заказы'"
text = "🗂 Мои заказы 🗂"

[buttons.in_work]
display_name = "Кнопка заказов 'в работе'"
text = "📘 В работе ⏳ "

[buttons.ready]
display_name = "Кнопка заказов 'готовы'"
text = "📙 Готовы к выдаче 📦"

[buttons.complete]
display_name = "Кнопка заказов 'завершен'"
text = "📗 Завершен ✅"

[buttons.points]
display_name = "Кнопка 'Наши пункты'"
text = "🖼 Наши пункты 🖼"

[buttons.feedback]
display_name = "Кнопка 'Оставить отзыв'"
text = "📝 Оставить отзыв 📝"

[buttons.feedbacks]
display_name = "Кнопка 'Отзывы'"
text = "📝 Отзывы 📝"

[buttons.faq]
display_name = "Кнопка 'FAQ'"
text = "🔎 Ответы на вопросы 🔎"

[buttons.contacts]
display_name = "Кнопка 'Контакты'"
text = "📱 Контакты 📱"

[buttons.support]
display_name = "Кнопка 'Поддержка'"
text = "🧑‍💻 Поддержка 🧑‍💻"

[ways]
ways = ["start", "menu", "info", "reg_begin", "get_fio", "get_phone", "get_email", 
        "user_agreement", "subscribe", "hand_over", "feedback",
        "orders", "in_work", "ready", "complete",
        "points", "faq", "contacts", "support"]

[keyboards]
keyboards_list = ["get_contact_keyboard", "start_keyboard", "info_keyboard", 
                "reg_back_keyboard", "user_agreement_keyboard", 
                "menu_keyboard", "orders_keyboard",
                "back_to_menu_keyboard",]

[keyboards.get_contact_keyboard]
buttons = ["button__contact"]
keyboard_type = "reply"

[keyboards.start_keyboard]
buttons = ["continue"]
ways = ["info"]
keyboard_type = "inline"

[keyboards.info_keyboard]
buttons = ["continue", "back"]
ways = ["reg_begin", "start"]
keyboard_type = "inline"

[keyboards.orders_keyboard]
buttons = ["in_work", "ready", "complete", "back"]
ways = ["in_work", "ready", "complete", "menu"]
keyboard_type = "inline"

[keyboards.reg_back_keyboard]
buttons = ["back"]
ways = ["info"]
keyboard_type = "inline"

[keyboards.user_agreement_keyboard]
buttons = ["agree"]
ways = ["subscribe"]
keyboard_type = "inline"

[keyboards.menu_keyboard]
buttons = ["hand_over", "my_orders", "points", "feedback", "faq", "contacts", "support"]
ways = ["hand_over", "orders", "points", "feedback", "faq", "contacts", "support"]
keyboard_type = "inline"

[keyboards.back_to_menu_keyboard]
buttons = ["menu"]
ways = ["start"]
keyboard_type = "inline"


[ways.start]
is_start = true
work_state = false
message = "first"
keyboard = "start_keyboard"
set_state = "union"
way_callback = "start"

[ways.info]
is_start = false
work_state = "union"
message = "info"
keyboard = "info_keyboard"
set_state = "union"
way_callback = "info"

[ways.reg_begin]
is_start = false
work_state = "union"
message = "write_fio"
keyboard = "reg_back_keyboard"
set_state = "fio"
way_callback = "reg_begin"

[ways.get_fio]
is_start = false
work_state = "fio"
message = "write_phone"
keyboard = "get_contact_keyboard"
set_state = "phone"
way_callback = false

[ways.get_phone]
is_start = false
work_state = "phone"
message = "user_agreement"
keyboard = "user_agreement_keyboard"
set_state = "union"
way_callback = false

[ways.get_email]
is_start = false
work_state = "email"
message = "user_agreement"
keyboard = "user_agreement_keyboard"
set_state = "union"
way_callback = false

[ways.user_agreement]
is_start = false
work_state = "end_reg"
message = "user_agreement"
keyboard = "user_agreement_keyboard"
set_state = "union"
way_callback = "user_agreement"

[ways.subscribe]
is_start = false
work_state = "union"
message = "subscribe"
keyboard = false
custom_keyboard = true
set_state = "union"
way_callback = "subscribe"

[ways.menu]
is_start = false
work_state = "union"
message = "menu"
keyboard = "menu_keyboard"
set_state = "union"
way_callback = "menu"

[ways.hand_over]
is_start = false
work_state = "union"
message = "our_points"
keyboard = false
custom_keyboard = true
set_state = "hand_over"
way_callback = "hand_over"

[ways.orders]
is_start = false
work_state = "union"
message = "my_orders"
keyboard = "orders_keyboard"
set_state = "union"
way_callback = "orders"

[ways.in_work]
is_start = false
work_state = "union"
message = "in_work"
keyboard = false
custom_keyboard = true
set_state = "union"
way_callback = "in_work"

[ways.ready]
is_start = false
work_state = "union"
message = "ready_issue"
keyboard = false
custom_keyboard = true
set_state = "union"
way_callback = "ready"

[ways.complete]
is_start = false
work_state = "union"
message = "completed"
keyboard = false
custom_keyboard = true
set_state = "union"
way_callback = "complete"

[ways.points]
is_start = false
work_state = "union"
message = "our_points"
keyboard = false
custom_keyboard = true
set_state = "union"
way_callback = "points"

[ways.feedback]
is_start = false
work_state = "union"
message = "feedback_points"
keyboard = false
custom_keyboard = true
set_state = "feedback"
way_callback = "feedback"

[ways.contacts]
is_start = false
work_state = "union"
message = "contacts"
keyboard = "back_to_menu_keyboard"
set_state = "union"
way_callback = "contacts"

[ways.support]
is_start = false
work_state = "union"
message = "support"
keyboard = "back_to_menu_keyboard"
set_state = "union"
way_callback = "support"

[ways.faq]
is_start = false
work_state = "union"
message = "faq"
keyboard = "back_to_menu_keyboard"
set_state = "union"
way_callback = "faq"
