# Generated by Django 5.0 on 2024-03-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionpoints',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='recept_icon/', verbose_name='Иконка'),
        ),
    ]
