# Generated by Django 5.0 on 2024-10-23 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_place', '0002_receptionpoints_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='external_order_information',
            field=models.TextField(default='', editable=False, verbose_name='Внешняя информация заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='issued_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_point_orders', to='model_place.receptionpoints', verbose_name='Точка выдачи'),
        ),
        migrations.AlterField(
            model_name='useritems',
            name='point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_items', to='model_place.receptionpoints', verbose_name='Точка'),
        ),
    ]
