# Generated by Django 5.0 on 2024-10-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_place', '0003_orders_external_order_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_link',
            field=models.TextField(default='', editable=False, verbose_name='Сслыка на оплату заказа'),
        ),
    ]
