# Generated by Django 5.0 on 2024-10-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_place', '0004_orders_order_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='external_order_information',
            field=models.TextField(default='', editable=False, null=True, verbose_name='Внешняя информация заказа'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_link',
            field=models.TextField(default='', editable=False, null=True, verbose_name='Сслыка на оплату заказа'),
        ),
    ]
